ALTER TABLE orders ALTER COLUMN id DROP DEFAULT;
ALTER TABLE orders ALTER COLUMN id SET DATA TYPE UUID USING id::text::uuid;
ALTER TABLE orders ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE inventory ALTER COLUMN id DROP DEFAULT;
ALTER TABLE inventory ALTER COLUMN id SET DATA TYPE UUID USING id::text::uuid;
ALTER TABLE inventory ALTER COLUMN id SET DEFAULT gen_random_uuid();