version: "3.8"

services:
  api-gateway:
    build:
      context: ../..
      dockerfile: api-gateway/Dockerfile
    container_name: rate-limiter-api-gateway
    restart: on-failure
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/Astracore/protocol/openid-connect/certs
    ports:
      - "8081:8080"
    networks:
      - Astracore-net

networks:
  Astracore-net:
    external: true